## Intro to tensors

In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.12.0


### Basics

In [3]:
rank_0_tensor = tf.constant(3)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
# A rank-1 tensor is a 1-axis vector
rank_1_tensor = tf.constant([1, 2, 3]) 
rank_1_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [5]:
# A matrix or rank-2 vector
rank_2_tensor = tf.constant([[1, 2, 3],
                             [4, 5, 6]])
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
# We can change the data type of the tensor
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4]], dtype=tf.float16)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [7]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [9]:
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[5,6],
                 [7,8]])
print(tf.add(a,b))
print(tf.multiply(a,b))
print(tf.matmul(a,b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [10]:
print(a + b) # element wise addition
print(a * b) # multiplication
print(a @ b) # matrix multiplication

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [11]:
c = tf.constant([[1.2, 3.4], 
                 [5.6, 7.8]])

# Finding largest value
print(tf.reduce_max(c))
# Finding index of larget value
print(tf.math.argmax(c))
# Compute softmax
print(tf.nn.softmax(c))

tf.Tensor(7.8, shape=(), dtype=float32)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor(
[[0.09975049 0.90024954]
 [0.09975047 0.90024954]], shape=(2, 2), dtype=float32)


In [18]:
# converting to tensor
print(tf.convert_to_tensor([1,2,3]))

a = np.array([1,2,3])
print(a)

# converts numpy arrays to tensor
print(tf.convert_to_tensor(a))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [19]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
print(f'dtype: {rank_4_tensor.dtype}')
print(f'Number of axes: {rank_4_tensor.ndim}')
print(f'Shape of tensor: {rank_4_tensor.shape}')
print(f'Total no.of elements: {tf.size(rank_4_tensor).numpy()}')

dtype: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Total no.of elements: 120


In [22]:
print(tf.rank(rank_4_tensor))

tf.Tensor(4, shape=(), dtype=int32)
